# Copyright Agustin K-ballo Berge, Fusion Fenix 2020
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Eggs.Invoke Benchmark

on:
  push:
    branches:
    paths:
      - 'CMakeLists.txt'
      - 'benchmark/**'
      - 'include/**'
      - '.github/workflows/invoke-benchmark.yml'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux GCC 9",
            os: ubuntu-latest,
            generator: Ninja,
            cc: "gcc-9", cxx: "g++-9",
            cxxflags: "-Wall -Wextra -Werror",
            buildflags: "-j1"
          }
        - {
            name: "Linux Clang 9",
            os: ubuntu-latest,
            generator: Ninja,
            cc: "clang-9", cxx: "clang++-9",
            cxxflags: "-Wall -Wextra -Werror",
            buildflags: "-j1"
          }
        - {
            name: "macOS Clang",
            os: macos-latest,
            generator: Ninja,
            cc: "clang", cxx: "clang++",
            cxxflags: "-Wall -Wextra -Werror",
            buildflags: "-j1"
          }
        - {
            name: "Windows MSVC 2019",
            os: windows-latest,
            generator: Visual Studio 16 2019,
            cc: "cl", cxx: "cl",
            cxxflags: "-W4 -WX -permissive-",
            buildflags: "-m:1"
          }

    steps:
    - uses: actions/checkout@v1

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
        CXXFLAGS: ${{ matrix.config.cxxflags }}
      run: |
        mkdir build
        cd build
        cmake -G"${{ matrix.config.generator }}" \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DBUILD_BENCHMARKS=ON \
            -DBENCHMARK_INSTANTIATIONS=10000 \
            -DBUILD_EXAMPLE=OFF \
            -DBUILD_TESTING=OFF \
            ..

    - name: Benchmark - function
      working-directory: build
      run: |
        cmake --build . --target benchmark.function \
            -- ${{ matrix.config.buildflags }}

    - name: Benchmark - member_object
      working-directory: build
      run: |
        cmake --build . --target benchmark.member_object \
            -- ${{ matrix.config.buildflags }}

    - name: Benchmark - member_function
      working-directory: build
      run: |
        cmake --build . --target benchmark.member_function \
            -- ${{ matrix.config.buildflags }}

    - name: Benchmark - callable
      working-directory: build
      run: |
        cmake --build . --target benchmark.callable \
            -- ${{ matrix.config.buildflags }}

    - name: Generate benchmark reports
      working-directory: build
      if: ${{ matrix.config.generator == 'Ninja' }}
      run: |
        cmake --build . --target benchmark

    - name: Upload benchmark reports
      if: ${{ matrix.config.generator == 'Ninja' }}
      uses: actions/upload-artifact@v2
      with:
        name: benchmark report - ${{ matrix.config.name }}
        path: |
          build/benchmark/benchmark.*.json
          build/benchmark/reports/
